# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['backend/app.py'],
    pathex=['backend'],
    binaries=[],
    datas=[
        ('backend/data/Accounts_and_Parcel_Numbers.csv', 'data'),
        ('backend/data/Address.dbf',                     'data'),
        ('backend/data/Address.shp',                     'data'),
        ('backend/data/Address.shx',                     'data'),
        ('backend/data/Address.prj',                     'data'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'transformers',
        'transformers.models.clip',
        'transformers.models.clip.modeling_clip',
        'transformers.models.clip.processing_clip',
        'torch',
        'torchvision',
        'PIL',
        'PIL.Image',
        'pillow_heif',
        'anthropic',
        'httpx',
        'httpx._transports.default',
        'anyio',
        'anyio._backends._asyncio',
        'certifi',
        'tokenizers',
        'pandas',
        'numpy',
        'struct',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'fastapi',
        'uvicorn',
        'playwright',
        'matplotlib',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AppraiserPhotoProcessor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,   # Shows a log window — change to False for final clean release
    icon=None,
)
